pcm.hw {
    @args [ CARD DEV ]
    @args.CARD { type string }
    @args.DEV { type integer default 0 }
    type hw
    card $CARD
    device $DEV
}

pcm.sysdefault {
    @args [ CARD ]
    @args.CARD { type string }
    type hw
    card $CARD
    device 0
}

pcm.default {
    type hw
    card 1
    device 0
}

ctl.hw {
    @args [ CARD ]
    @args.CARD { type string }
    type hw
    card $CARD
}

ctl.default {
    type hw
    card 1
}

seq.default {
    type hw
}

seq.hw {
    type hw
}
